### PR TITLE
Issue 198 fix

### LINKED ISSUE #198: Cookie problem when original server is localhost
For instance when using OXAR my original server is localhost:50443. 
Launching a project creates a proxy to localhost:4000.

The problem is: [Cookies are not port specific](http://stackoverflow.com/questions/1612177/are-http-cookies-port-specific) so both URLs (localhost:4000 and localhost:50443) are sharing the same cookie, which ends up with #APP_IMAGES# pointing to locahost:4000 even if your on localhost:50443.

I tried adding some logic to the application process to check the port manually but `owa_util.print_cgi_env` doesn't provide port information from the proxy.

@martindsouza Any thoughts? For now I'm thinking this is going to be a limitation of this project.

### PR DESCRIPTION
**Pull request by fuzziebrain**
@vincentmorneau I'm hoping this would resolve #198 . Tested to work on my OXAR setup.

### CODE REVIEW

**Comment by vincentmorneau** [comment]
Very interesting approach! This makes me think, do we even need a cookie? What if we had something like:

```
begin
	if owa_util.get_cgi_env('X-Nitrified') is not null then
		-- Use one of the following depending on your files location
		-- apex_application.g_flow_images := owa_util.get_cgi_env('X-Nitrified');
		-- apex_application.g_company_images := owa_util.get_cgi_env('X-Nitrified');
		-- apex_application.g_theme_file_prefix := owa_util.get_cgi_env('X-Nitrified');
		-- :G_APP_IMAGES := owa_util.get_cgi_env('X-Nitrified');
	end if;
end;
```

Thoughts?

**Comment by fuzziebrain** [comment]
I wondered about that myself. Your call!

**Comment by martindsouza** [comment]
@fuzziebrain very cool idea. @vincentmorneau I agree we may not event need a cookie. If you do use CGI I'd recommend something explicit like `apex_nitro_img_prefix`. 

We may also want to do some speed tests to compare the call time of `owa_util.get_cgi_env` vs `l_cookie := owa_cookie.get('oos-apex-nitro');`. If someone doesn't use build options to disable the region this could come into play. Minor problem (since BOs are supposed to be used) but something to think of.

**Comment by vincentmorneau** [comment]
@fuzziebrain thank you so much for the inspiration. I have restructured the code too much so I can't accept the PR now, but I gotta give you all the credit!

**Comment by fuzziebrain** [comment]
Glad I could help!

**Pull request closed without merging**
